GET http://localhost:3001/

###

POST http://localhost:3001/newPiece
Content-Type: application/json

{
    "book": 2,
    "pieceName": "Test Piece",
    "techniqueTags": ["test1", "test2"]   
}
###

POST http://localhost:8080/addGame
Content-Type: application/json

{
    "gameName": "Dominoes 2",
    "gameText": "You know how to play",
    "gameTechnique": ["listening"],
    "gamePieces": ["Variation A", "Variation B"],
    "saveUser": "12345"
}
###
POST http://localhost:8080/getUserCreatedGames
Content-Type: application/json

{
    "userId": "640a5a73f25281359a864e54"
}

###
POST http://localhost:8080/getSavedGames
Content-Type: application/json

{
    "saveUser": "640a5a73f25281359a864e54"
}

###

GET http://localhost:8080/getGameTechniques

###
GET http://localhost:8080/getOneUserGame/64282a3760c7ef0c5c686de3

###
POST http://localhost:8080/trackVote
Content-Type: application/json

{
    "gameId": "64354f5e4d31dbd8d3f93049",
    "updateVoteValue": 1,
    "userId": "640a5a73f25281359a864e59"
}

###
GET http://localhost:8080/getVoteTotals
